import type { Product, Collection, Category, Banner, Coupon, Order, Customer, Settings } from "./types";
import { IMG } from "./brand-images";

export const seedCategories: Category[] = [
  { id: "blusas", name: "Blusas" },
  { id: "bodies", name: "Bodies" },
  { id: "conjuntos", name: "Conjuntos" },
  { id: "vestidos", name: "Vestidos" },
  { id: "calcas", name: "Calças" },
];

export const seedCollections: Collection[] = [
  {
    id: "segunda-pele",
    name: "Segunda Pele",
    description: "Malha canelada de alta compressão. O corte que acompanha o corpo sem apertar.",
    image: IMG.caneladaOff,
    featured: true,
  },
  {
    id: "noite",
    name: "Noite",
    description: "Recortes, amarrações e couro. Peças pensadas para começar tarde.",
    image: IMG.vestidoCurto,
    featured: true,
  },
  {
    id: "denim",
    name: "Denim",
    description: "Modelagens amplas e lavagens profundas para o dia inteiro.",
    image: IMG.jeansBaggy,
    featured: true,
  },
  {
    id: "editorial",
    name: "Editorial Neon",
    description: "A cara da marca em luz rosa: atitude, brilho e corte preciso.",
    image: IMG.neon,
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    name: "Body Decote Transpassado",
    price: 189,
    category: "bodies",
    collectionId: "segunda-pele",
    description: "Body em malha canelada com decote transpassado e alças finas. Cavado nas laterais, acabamento em viés.",
    images: [IMG.bodyGrafite, IMG.bodyGrafiteAlt],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Grafite", "Preto"],
    featured: true,
    isNew: true,
    stock: 12,
  },
  {
    id: "p2",
    name: "Blusa Canelada Manga Longa",
    price: 149,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Blusa em canelado fino com decote quadrado e manga longa com passa-dedo. Caimento segunda pele.",
    images: [IMG.caneladaOff, IMG.caneladaOffAlt, IMG.caneladaOffCostas, IMG.caneladaOffLook],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Off White", "Preto"],
    featured: true,
    isNew: true,
    stock: 18,
  },
  {
    id: "p3",
    name: "Cropped Tomara Que Caia",
    price: 129,
    category: "blusas",
    collectionId: "denim",
    description: "Cropped tomara que caia em malha estruturada com elástico interno. Fica no lugar o dia todo.",
    images: [IMG.croppedTomara, IMG.jeansBaggyAlt],
    sizes: ["PP", "P", "M"],
    colors: ["Preto"],
    stock: 10,
  },
  {
    id: "p4",
    name: "Body Recorte Cut-Out",
    price: 199,
    category: "bodies",
    collectionId: "noite",
    description: "Body preto com recorte frontal, alças cruzadas e costas fechadas. Peça-chave da noite.",
    images: [IMG.bodyCutout, IMG.bodyCutoutAlt],
    sizes: ["P", "M", "G"],
    colors: ["Preto"],
    featured: true,
    isNew: true,
    stock: 8,
  },
  {
    id: "p5",
    name: "Blusa Gola Alta Canelada",
    price: 159,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Gola alta em canelado com barra franzida e manga longa ajustada.",
    images: [IMG.golaAltaOff],
    sizes: ["P", "M", "G"],
    colors: ["Off White"],
    stock: 14,
  },
  {
    id: "p6",
    name: "Blusa Ombro a Ombro",
    price: 149,
    category: "blusas",
    collectionId: "noite",
    description: "Ombro a ombro com manga longa e barra cropped. Malha com toque acetinado.",
    images: [IMG.ombroAOmbro, IMG.ombroAOmbroAlt],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Preto"],
    featured: true,
    stock: 11,
  },
  {
    id: "p7",
    name: "Blusa Decote Quadrado",
    price: 149,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Decote quadrado amplo, manga longa e modelagem justa. O básico que sustenta o look.",
    images: [IMG.decoteQuadrado, IMG.decoteQuadradoAlt],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Off White", "Areia"],
    stock: 16,
  },
  {
    id: "p8",
    name: "Top Renda Alça Fina",
    price: 119,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Top de alça fina com detalhe em renda no decote e na barra.",
    images: [IMG.topRenda, IMG.topRendaAlt],
    sizes: ["PP", "P", "M"],
    colors: ["Preto"],
    isNew: true,
    stock: 20,
  },
  {
    id: "p9",
    name: "Blusa Segunda Pele Chocolate",
    price: 149,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Malha lisa em tom chocolate, manga longa com passa-dedo e gola alta discreta.",
    images: [IMG.chocolate, IMG.chocolateAlt, IMG.chocolateLook],
    sizes: ["P", "M", "G"],
    colors: ["Chocolate"],
    stock: 9,
  },
  {
    id: "p10",
    name: "Blusa Tachas Ombro Único",
    price: 169,
    category: "blusas",
    collectionId: "noite",
    description: "Assimétrica de ombro único com fileira de tachas metálicas.",
    images: [IMG.tachas],
    sizes: ["P", "M", "G"],
    colors: ["Off White"],
    isNew: true,
    stock: 6,
  },
  {
    id: "p11",
    name: "Conjunto Cropped + Saia Off White",
    price: 259,
    category: "conjuntos",
    collectionId: "segunda-pele",
    description: "Conjunto em canelado: cropped manga longa e saia curta de cintura alta.",
    images: [IMG.conjuntoOff, IMG.conjuntoOffAlt],
    sizes: ["P", "M", "G"],
    colors: ["Off White"],
    featured: true,
    stock: 7,
  },
  {
    id: "p12",
    name: "Vestido Curto Gola Alta",
    price: 229,
    category: "vestidos",
    collectionId: "noite",
    description: "Vestido curto em malha grossa com gola alta, manga longa e costas fechadas.",
    images: [IMG.vestidoCurto, IMG.vestidoCurtoCostas],
    sizes: ["P", "M", "G"],
    colors: ["Preto"],
    featured: true,
    isNew: true,
    stock: 8,
  },
  {
    id: "p13",
    name: "Blusa Amarração nas Costas",
    price: 159,
    category: "blusas",
    collectionId: "noite",
    description: "Frente franzida com amarração e costas abertas com tiras. Fecha o look sem esforço.",
    images: [IMG.amarracao, IMG.amarracaoCostas],
    sizes: ["PP", "P", "M"],
    colors: ["Preto"],
    stock: 10,
  },
  {
    id: "p14",
    name: "Vestido Longo Alça Fina",
    price: 279,
    category: "vestidos",
    collectionId: "noite",
    description: "Vestido longo em malha firme, alça fina e fenda lateral. Silhueta alongada.",
    images: [IMG.vestidoLongo, IMG.vestidoLongoAlt],
    sizes: ["P", "M", "G"],
    colors: ["Preto"],
    stock: 5,
  },
  {
    id: "p15",
    name: "Conjunto Cut-Out Preto",
    price: 269,
    category: "conjuntos",
    collectionId: "noite",
    description: "Cropped com recortes vazados e saia curta de cintura alta. Conjunto para a noite.",
    images: [IMG.conjuntoCutout, IMG.conjuntoCutoutAlt],
    sizes: ["P", "M"],
    colors: ["Preto"],
    isNew: true,
    stock: 6,
  },
  {
    id: "p16",
    name: "Calça Couro Cintura Alta",
    price: 249,
    category: "calcas",
    collectionId: "noite",
    description: "Calça em couro ecológico com cintura alta e caimento reto.",
    images: [IMG.calcaCouro, IMG.calcaCouroAlt],
    sizes: ["36", "38", "40", "42"],
    colors: ["Preto"],
    featured: true,
    stock: 9,
  },
  {
    id: "p17",
    name: "Calça Jeans Baggy Black",
    price: 219,
    category: "calcas",
    collectionId: "denim",
    description: "Jeans baggy em lavagem black, cintura alta e pernas amplas com barra larga.",
    images: [IMG.jeansBaggy, IMG.jeansBaggyAlt],
    sizes: ["36", "38", "40", "42"],
    colors: ["Black"],
    isNew: true,
    stock: 12,
  },
  {
    id: "p18",
    name: "Blusa Manga Longa Grafite",
    price: 139,
    category: "blusas",
    collectionId: "segunda-pele",
    description: "Manga longa em malha grafite com decote quadrado e barra cropped.",
    images: [IMG.blusaGrafite],
    sizes: ["PP", "P", "M", "G"],
    colors: ["Grafite"],
    stock: 15,
  },
];

export const seedBanners: Banner[] = [
  {
    id: "b1",
    title: "Segunda Pele",
    subtitle: "A malha que acompanha o corpo. Nova coleção Wiskow.",
    image: IMG.bodyCutout,
    cta: "Descobrir",
    href: "/nova-colecao",
    order: 1,
  },
  {
    id: "b2",
    title: "Conjuntos",
    subtitle: "Um look inteiro em duas peças.",
    image: IMG.conjuntoOff,
    cta: "Ver coleção",
    href: "/colecoes",
    order: 2,
  },
  {
    id: "b3",
    title: "Editorial Neon",
    subtitle: "Atitude em luz rosa.",
    image: IMG.neon,
    cta: "Ver catálogo",
    href: "/catalogo",
    order: 3,
  },
];

export const seedCoupons: Coupon[] = [
  { id: "c1", code: "WISKOW10", discount: 10, active: true },
  { id: "c2", code: "PRIMEIRA", discount: 15, active: true },
];

export const seedOrders: Order[] = [
  { id: "o1", customer: "Marina Ribeiro", total: 597, status: "Pago", date: "2025-11-14", items: 3 },
  { id: "o2", customer: "Camila Duarte", total: 189, status: "Enviado", date: "2025-11-12", items: 1 },
  { id: "o3", customer: "Julia Prado", total: 448, status: "Pendente", date: "2025-11-10", items: 2 },
  { id: "o4", customer: "Beatriz Lemos", total: 866, status: "Entregue", date: "2025-11-08", items: 4 },
  { id: "o5", customer: "Sofia Andrade", total: 229, status: "Pago", date: "2025-11-07", items: 1 },
];

export const seedCustomers: Customer[] = [
  { id: "cu1", name: "Marina Ribeiro", email: "marina@example.com", phone: "+55 51 9 9999-0001", orders: 4, spent: 1890 },
  { id: "cu2", name: "Camila Duarte", email: "camila@example.com", phone: "+55 51 9 9999-0002", orders: 2, spent: 738 },
  { id: "cu3", name: "Julia Prado", email: "julia@example.com", phone: "+55 51 9 9999-0003", orders: 1, spent: 448 },
  { id: "cu4", name: "Beatriz Lemos", email: "beatriz@example.com", phone: "+55 51 9 9999-0004", orders: 6, spent: 2710 },
];

export const defaultSettings: Settings = {
  storeName: "Wiskow Concept",
  whatsapp: "5551997593705",
  instagram: "wiskow.concept",
  logo: "/__l5e/assets-v1/d19089d1-ca9c-47f7-8d3c-901d4ab93959/wiskow-wordmark.png",
  primaryColor: "#fdb9e2",
  heroBannerId: "b1",
  featuredCollectionIds: ["segunda-pele", "noite", "denim"],
  featuredProductIds: ["p2", "p4", "p12", "p11"],
};
